runner:
  credo:
    cmd: mix credo suggest --strict --format=flycheck
    errorformat:
      - "%f:%l:%c: %t: %m"
      - "%f:%l: %t: %m"

  eslint:
    cmd: npm run eslint --prefix=assets --silent
    format: rdjson
