runner:
  credo:
    cmd: mix credo suggest --strict --format=flycheck
    errorformat:
      - "%f:%l:%c: %t: %m"
      - "%f:%l: %t: %m"

  eslint:
    cmd: npm run eslint --prefix=assets --silent
    format: rdjson

  stylelint:
    cmd: npm run stylelint --prefix=assets --silent
    # format: eslint-compact
    errorformat:
      - "%f: line %l, col %c, %trror - %m"
