branch-defaults:
  master:
    environment: Phxactions-env
global:
  application_name: Phx Actions
  branch: master
  default_platform: Docker 18.09.9-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: rafaeliga
  repository: null
  sc: git
  workspace_type: Application
