name: "Docker"
description: "docker"
runs:
  using: "composite"
  steps:
    - name: Download compiled
      uses: actions/download-artifact@v2
      with:
        name: compiled
        path: _build/${{ env.MIX_ENV }}/rel/phx_actions

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ GITHUB_SHA }}-${{ env.MIX_ENV }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-${{ env.MIX_ENV }}
          type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        file: priv/setup/docker/Dockerfile
        context: .
        build-args: |
          ENVIRONMENT=${{ env.MIX_ENV }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
