name: AWS deploy

on:
  push:
    branches: [master]

env:
  APP_NAME: Phx Actions
  AWS_REGION: us-east-1
  AWS_PLATFORM: Docker
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6 (needed for eb cli)
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          echo ${{secrets.AWS_ACCESS_KEY_ID}}

          python -m pip install --upgrade pip
          pip install awsebcli --upgrade

          envsubst < priv/setup/aws/Dockerrun.aws.json > ./Dockerrun.aws.json

          eb use Phxactions-env

          envsubst < priv/setup/aws/eb.env > .ebextensions/options.config

          git add ./Dockerrun.aws.json .ebextensions/options.config

          eb status
          eb deploy --staged
          eb printenv
