name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "ENV to deploy"
        required: true
        default: "hom"

jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    env:
      AWS_EB_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_EB_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENDPOINT_HOST: ${{ secrets.ENDPOINT_HOST }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      USE_SSL: true

    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6 (needed for eb cli)
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Configure credentials
        run: |
          echo $GITHUB_ENV
          mkdir ~/.aws
          envsubst < priv/setup/aws/aws.env > ~/.aws/credentials
      - name: Install eb cli
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
      - name: Prepare deploy
        run: |
          envsubst < priv/setup/aws/Dockerrun.aws.json > ./Dockerrun.aws.json

          eb use phxactions-$GITHUB_ENV

          envsubst < priv/setup/aws/eb.env > .ebextensions/options.config

          git add ./Dockerrun.aws.json .ebextensions/options.config
      - name: Check EB status
        run: eb status

      - name: Deploy
        run: |
          eb deploy --staged
          eb printenv
