name: Github Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release body
        run: |
          echo "RELEASE_DESCRIPTION=$(sed '1,/## \['${{ github.ref_name }}'\]/d;/## \[v.*\]/Q' CHANGELOG.md)" >> $GITHUB_ENV

      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(process.env)
            console.log(process.env.RELEASE_DESCRIPTION)

            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              name: "${{ github.ref }}",
              tag_name: "${{ github.ref }}",
              body: "test new body"
            });
