name: NodeJS CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.1"

      - name: Build
        run: |
          npm ci --prefix=assets
          npm run build --if-present --prefix=assets
      - name: Test
        run: npm test --prefix=assets
