name: Release prod

on:
  push:
    branches: [master]

env:
  MIX_ENV: prod
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-phoenix:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/release-hom.yml
