name: Tests

on: [pull_request]

env:
  MIX_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

jobs:
  elixir:
    runs-on: ubuntu-latest

    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: "1.12.2"
          otp-version: "23.3"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-elixir
          restore-keys: ${{ runner.os }}-build-elixir
      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: |
          mix test --cover
      - name: Coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./cover/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
  nodejs:
    needs: elixir
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.1"

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-elixir
          restore-keys: ${{ runner.os }}-build-elixir

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: assets/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/assets/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Build
        run: |
          npm install --prefix assets
          npm run build --prefix assets
      - name: Test
        run: npm test --prefix=assets

  code_quality:
    needs: nodejs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-elixir
          restore-keys: ${{ runner.os }}-build-elixir

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: assets/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/assets/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -diff="git diff FETCH_HEAD" -reporter=github-pr-review -tee
