name: Tests

on: [pull_request]

env:
  MIX_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

jobs:
  elixir:
    runs-on: ubuntu-latest

    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: "1.12.2"
          otp-version: "23.3"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: |
          mix test --cover
          mix coveralls.xml
          cp cover/excoveralls.xml coverage.xml
      - name: Changed Files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check test coverage
        uses: AveryCameronUofR/test-coverage-check-gh-action@1.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          # minNewCoverage: 0.8 (Optional, 0.8 default)
          # maxCoverageChange: 0.1 (Optional, 0.1 default)
      - name: Upload deps result
        uses: actions/upload-artifact@v2
        with:
          name: elixir-deps
          path: deps
  nodejs:
    needs: elixir
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.1"

      - name: Download deps result
        uses: actions/download-artifact@v2
        with:
          name: elixir-deps
          path: deps

      - name: Build
        run: |
          npm install --prefix assets
          npm run build --prefix assets
      - name: Test
        run: npm test --prefix=assets
